// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byzdpzcynaenmustqfds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5emRwemN5bmFlbm11c3RxZmRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjE2ODgsImV4cCI6MjA2OTM5NzY4OH0.UTHEiImISTrCMw2rSpYw8XfSF6uIdATussLVh5NEOzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});